{{- if .Values.uiProxy.enabled }}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "platform-ipam.fullname" . }}-ui-proxy
  labels:
    {{- include "platform-ipam.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "platform-ipam.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ui-proxy
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.uiProxy.networkPolicy.ingress.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.uiProxy.networkPolicy.ingress.podSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.dns.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.dns.podSelector | nindent 12 }}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- range .Values.uiProxy.networkPolicy.egress }}
    - to:
        - ipBlock:
            cidr: {{ .cidr | quote }}
      ports:
        {{- toYaml .ports | nindent 8 }}
    {{- end }}
{{- end }}
{{- end }}
