#!/usr/bin/env sh
set -eu

target=${1:-.env}
if [ -e "$target" ]; then
  printf '%s already exists; refusing to overwrite it\n' "$target" >&2
  exit 1
fi
project=${COMPOSE_PROJECT_NAME:-platform-ipam-dev}
if command -v docker >/dev/null 2>&1 && docker volume inspect "${project}_netbox-db-data" >/dev/null 2>&1; then
  printf '%s already exists; refusing to generate credentials that may not match it\n' "${project}_netbox-db-data" >&2
  printf '%s\n' 'Restore the prior .env, or back up and explicitly reset the disposable development stack.' >&2
  exit 1
fi
umask 077
token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif [ -r /dev/urandom ] && command -v od >/dev/null 2>&1; then
    od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
  else
    printf '%s\n' 'openssl or od with /dev/urandom is required to create development secrets' >&2
    exit 1
  fi
}
# NetBox rejects an API token pepper shorter than 50 characters and refuses to
# start. Fail here rather than leaving an unusable stack behind.
pepper() {
  value=$(token)
  if [ "${#value}" -lt 50 ]; then
    printf '%s\n' 'generated NetBox API token pepper is shorter than the required 50 characters' >&2
    exit 1
  fi
  printf '%s\n' "$value"
}
# NetBox validates a v1 API token's plaintext at exactly 40 characters, and
# the platform adapter authenticates with the v1 "Token <secret>" header.
netbox_token() {
  token | cut -c1-40
}
cat > "$target" <<EOF
COMPOSE_PROJECT_NAME=platform-ipam-dev
PLATFORM_DB_USER=platform_ipam
PLATFORM_DB_PASSWORD=$(token)
PLATFORM_DB_NAME=platform_ipam
IPAM_ENVIRONMENT=development
IPAM_AUTH_MODE=local
IPAM_LOCAL_TOKEN=$(token)
IPAM_LOCAL_SUBJECT=developer
IPAM_OPS_TOKEN=$(token)
IPAM_OPERATOR_TOKEN=$(token)
IPAM_AWS_MODE=fake
IPAM_LISTEN_ADDR=:8080
IPAM_CONFIG_FILE=/etc/platform-ipam/config/pools.yaml
IPAM_NETBOX_URL=http://netbox:8080
IPAM_NETBOX_TOKEN=$(netbox_token)
IPAM_OIDC_ISSUER=
IPAM_OIDC_AUDIENCE=
IPAM_IDENTITY_FILE=/etc/platform-ipam/identity/identities.yaml
NETBOX_DB_PASSWORD=$(token)
NETBOX_REDIS_PASSWORD=$(token)
NETBOX_CACHE_PASSWORD=$(token)
NETBOX_SECRET_KEY=$(token)
NETBOX_API_TOKEN_PEPPER=$(pepper)
NETBOX_SUPERUSER_NAME=admin
NETBOX_SUPERUSER_EMAIL=admin@example.invalid
NETBOX_SUPERUSER_PASSWORD=$(token)
NETBOX_PORT=18000
NETBOX_E2E_VIEWER_TOKEN=$(netbox_token)
NETBOX_E2E_MAINTAINER_TOKEN=$(netbox_token)
# ui-proxy basic-auth credential (package A3, docs/GUI_AUTHENTICATION.md).
# Only the plaintext is stored here; ui-proxy/entrypoint.sh hashes it with
# bcrypt at container start, so no hash needs to be regenerated by hand when
# this is rotated.
NETBOX_UI_USER=operator
NETBOX_UI_PASSWORD=$(token)
EOF
printf 'Wrote development environment to %s\n' "$target"
